#自定义配置
mywebmvc:
  cros: http://localhost:3000,http://localhost:5173,http://localhost:9001

#spring配置
spring:
  profiles:
    active: dev
  application:
    name: niceplace-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/niceplace?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置
  redis:
    port: 6379
    host: 123.123.123.123
    database: 15

#web服务器配置(与浏览器相关的)
server:
  port: 8081
  #设置servlet
  servlet:
    #设置进入web服务器前url加一层
    context-path: /api
    session:
      cookie:
        #cookie在domain指定的ip进行共享
        domain: localhost

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

